# Socless core infrastructure and functions
service: socless

provider:
  name: aws
  runtime: python3.7
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}"
  stage: ${{opt:stage}}
  region: ${{opt:region}}
  deploymentBucket: socless-${{opt:stage}}-deployments
  deploymentPrefix: core
  role:
    ${{ssm:/socless/iam/arn}}
  versionFunctions: false
  memorySize: 128
  timeout: 10
  environment:
    SOCLESS_VAULT:
      Ref: SoclessVault
    SOCLESS_RESULTS_TABLE:
      Ref: ExecutionResultsTable
  vpc:
    securityGroupIds:
      - ${{ssm:/socless/${{opt:stage}}/sgId}} # El security group id esta en una variable de SSM
    subnetIds:
      - ${{ssm:/socless/${{opt:stage}}/privateSubnet}} # El subnet id esta en una variable de SSM

plugins:
  - serverless-package-python-functions


custom:
  pkgPyFuncs:
    buildDir: build
    abortOnPackagingErrors: true
    globalRequirements:
      - ./functions/requirements.txt

resources:
  - ${{file(resources/dynamodb.yml)}} # DynamoDB Tables
  - ${{file(resources/sfn.yml)}} # Step Functions Resources
  - ${{file(resources/s3.yml)}} # S3 Resources
  - ${{file(resources/kms.yml)}} # KMS Resources
  - ${{file(resources/apigateway.yml)}} # API Gateway
  - Outputs:
      MergeParallelOutput:
        Description: Merges the output from a parallel state into a unified object
        Value:
          Fn::Sub: ${MergeParallelOutputLambdaFunction.Arn}

      SaveMessageResponseToken:
        Description: Save the task token created when the Socless Messages Response Activity state is used
        Value:
          Fn::Sub: ${SaveMessageResponseTokenLambdaFunction.Arn}

      Counter:
        Description: Simple counter functionality
        Value:
          Fn::Sub: ${CounterLambdaFunction.Arn}

      SetInvestigationStatus:
        Description: Set the internal status of an Socless investigation
        Value:
          Fn::Sub: ${SetInvestigationStatusLambdaFunction.Arn}

      AddCustomMapping:
        Description: Add a custom mapping to the CustomMappings Table
        Value:
          Fn::Sub: ${AddCustomMappingLambdaFunction.Arn}

      QueryCustomMapping:
        Description: Retrieve a custom mapping from the CustomMappings Table
        Value:
          Fn::Sub: ${QueryCustomMappingLambdaFunction.Arn}

      CreateEvents:
        Description: Create events from within a playbook
        Value:
          Fn::Sub: ${CreateEventsLambdaFunction.Arn}

      CacheResults:
        Description: Cache returned results
        Value:
          Fn::Sub: ${CacheResultsLambdaFunction.Arn}
      SoclessLogFindings:
        Description: Generate and upload SOCless log findings to a logging bucket
        Value:
          Fn::Sub: ${SoclessLogFindingsLambdaFunction.Arn}

      StatesExecutionRoleArn:
        Description: Arn of the StatesExecutionRole
        Value:
          Fn::Sub: ${{ssm:/socless/iam/arn2}}

package:
  individually: true

functions:
  MergeParallelOutput:
    handler: lambda_function.lambda_handler
    name: _socless_merge_parallel_output
    description: Merges the output from a Parallel state into a unified object
    package:
      include:
        - functions/merge_parallel_output
      artifact: ${{self:custom.pkgPyFuncs.buildDir}}/${{self:functions.MergeParallelOutput.name}}.zip

  SaveMessageResponseToken:
    handler: lambda_function.lambda_handler
    name: _socless_save_msg_resp_token
    description: Save the task token created when the Socless Messages Response Activity state is used
    environment:
     AWAIT_MESSAGE_RESPONSE_ARN:
       Ref: AwaitMessageResponseActivity
     MESSAGE_RESPONSES_TABLE:
       Ref: MessageResponsesTable
    package:
     include:
       - functions/save_msg_resp_token
     artifact: ${{self:custom.pkgPyFuncs.buildDir}}/${{self:functions.SaveMessageResponseToken.name}}.zip

  Counter:
    handler: lambda_function.lambda_handler
    name: _socless_counter
    description: Simple counter functionality
    package:
      include:
        - functions/counter
      artifact: ${{self:custom.pkgPyFuncs.buildDir}}/${{self:functions.Counter.name}}.zip

  SetInvestigationStatus:
    handler: lambda_function.lambda_handler
    name: socless_set_investigation_status
    environment:
      SOCLESS_EVENTS_TABLE:
        Ref: EventsTable
    description: Socless integration to set an investigations status
    package:
      include:
        - functions/set_investigation_status
      artifact: ${{self:custom.pkgPyFuncs.buildDir}}/${{self:functions.SetInvestigationStatus.name}}.zip

  Playground:
    handler: lambda_function.lambda_handler
    name: _socless_playground
    description: Function for playing around with Socless' Configuration
    package:
      include:
        - functions/playground
      artifact: ${{self:custom.pkgPyFuncs.buildDir}}/${{self:functions.Playground.name}}.zip

  AddCustomMapping:
    handler: lambda_function.lambda_handler
    name: socless_add_custom_mapping
    description: Add a custom mapping to the CustomMappings Table
    environment:
      SOCLESS_CUSTOM_MAPPINGS_TABLE:
        Ref: CustomMappingsTable
    package:
      include:
        - functions/add_custom_mapping
      artifact: ${{self:custom.pkgPyFuncs.buildDir}}/${{self:functions.AddCustomMapping.name}}.zip

  QueryCustomMapping:
    handler: lambda_function.lambda_handler
    name: socless_query_custom_mapping
    description: Retrieve a custom mapping from the CustomMappings Table
    environment:
      SOCLESS_CUSTOM_MAPPINGS_TABLE:
        Ref: CustomMappingsTable
    package:
      include:
        - functions/query_custom_mapping
      artifact: ${{self:custom.pkgPyFuncs.buildDir}}/${{self:functions.QueryCustomMapping.name}}.zip

  CreateEvents:
    handler: lambda_function.lambda_handler
    name: socless_create_events
    description: Create events from within a playbook
    memorySize: 512
    timeout: 300
    environment:
      SOCLESS_EVENTS_TABLE:
        Ref: EventsTable
      SOCLESS_PLAYBOOKS_TABLE:
        Ref: PlaybooksTable
    package:
      include:
        - functions/create_events
      artifact: ${{self:custom.pkgPyFuncs.buildDir}}/${{self:functions.CreateEvents.name}}.zip

  CacheResults:
    handler: lambda_function.lambda_handler
    name: socless_cache_results
    description: Cache return results
    package:
      include:
        - functions/cache_results
      artifact: ${{self:custom.pkgPyFuncs.buildDir}}/${{self:functions.CacheResults.name}}.zip

  SoclessLogFindings:
    handler: lambda_function.lambda_handler
    name: socless_log_findings
    description: Generate and upload SOCless log findings to a logging bucket
    environment:
      SOCLESS_Logs:
        Ref: SoclessLogs
    package:
      include:
        - functions/socless_log_findings
      artifact: ${{self:custom.pkgPyFuncs.buildDir}}/${{self:functions.SoclessLogFindings.name}}.zip
